### ISSUE TITLE
How to improve accuracy?

### ISSUE THREAD

**Issue by jingshaojing** [KumarRobotics/msckf_vio#117]
First , Thank you very much for your work. It is really a good work . I use D435i for this project. In my view, it may seems work, it has achieved a certain effect in my opinion, but when comparing GPS and RTK, the accuracy is not very satisfactory.
I have tried to modify the following parameters to achieve the current effect:
`"noise/gyro" `   `"noise/acc"`   ` "noise/gyro_bias"`  ` "noise/acc_bias"`  ` "initial_covariance/gyro_bias" `   `"initial_covariance/acc_bias"`  ` "initial_covariance/extrinsic_rotation_cov" `  ` "initial_covariance/extrinsic_translation_cov" `
`"grid_min_feature_num" `   `"grid_max_feature_num" `  ` "max_iteration"`    `"ransac_threshold"`

The following three  pictures are my own test data after referring to all the parameters that can be modified in the issue:
![ApplicationFrameHost_Kj0YXRyzAQ](https://user-images.githubusercontent.com/34829689/123661884-7e78a900-d867-11eb-9eb5-5ae77efde83e.png)
![ApplicationFrameHost_HSphdd3wUv](https://user-images.githubusercontent.com/34829689/123661929-89cbd480-d867-11eb-90ff-298cfbc71fd6.png)
![ApplicationFrameHost_cblyIvvkLZ](https://user-images.githubusercontent.com/34829689/123661940-8df7f200-d867-11eb-9243-77679e726e8e.png)

_**So what parameters can I adjust to get better results？**_  Thank you.

**Comment by ke-sun** [comment]
That's a tricky question for which I am afraid I don't have a good answer. It depends on lots of factors like testing environments, motion of the sensor, and properties of the actual hardware, etc.

Just based on the attached images, it seems features are tracked and matched fine. The estimated orientation are mostly correct. It's the translation that drifts more than expected. I would try to tune the acceleration noise together with the feature noise to see which one should be relied on more in order to reduce translation error.

With that being said, it is expected for visual inertial odometry to have large error using sensors like D435i given its short stereo baseline and low cost IMU. In case much more accurate estimation is required, loop closure might be necessary.

**Comment by jingshaojing** [comment]
Thanks for your advice!
