### ISSUE TITLE
catkin_make & catkin_make --pkg msckf_vio --cmake-args -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by gyjun0230** [KumarRobotics/msckf_vio#21]
Hello , i got a strange problem. I build the msckf_vio package with catkin_make, the VIO result being very poor. However , if I build the package  with it（catkin_make --pkg msckf_vio --cmake-args -DCMAKE_BUILD_TYPE=Release）， the result is good. So , that's why???

**Comment by kartikmohta** [comment]
Without `--cmake-args -DCMAKE_BUILD_TYPE=Release`, it builds without compiler optimizations which leads to bad performance. For any benchmarks, you should build in `Release` mode.

**Comment by gyjun0230** [comment]
Thank you very much for replying me. The program is very well and grate you to share for everyone to use.
I only understand the use of debug or release affect the speed of the program, but the results should not be  affected. I'm very curious. Thank you very much!

**Comment by SongBiaoVision** [comment]
Hello, Do you run the program in Euroc datasets or device? @gyjun0230

**Comment by biendltb** [comment]
I faced the same issue with the build flag and also wondered how it relates to the compiler optimization. How could we detect if the accuracy is affected by the run-time performance since there are no obvious clues when it happens.

**Comment by kartikmohta** [comment]
The main problem when compiling without optimizations is that the computation takes a long time for every frame so if you play a bag at normal speed, a lot of frames might be skipped which would lead to bad accuracy.

**Comment by biendltb** [comment]
Thanks for the reply, @kartikmohta.
I think that the issue might also come from a mechanism in the algorithm or one of its dependent libraries since I didn't expect the result is at that poor. I could see the algorithm run slightly slower but a very dramatic drift occurs even with the slightest movement of the camera. Let's say if I feed a stream of data at 10 FPS and the algorithm can only handle 7 FPS, the drift is still much worse than playing a 7-FPS rosbag.
I'm trying to understand deeper about the error caused by this build flag.

**Comment by kartikmohta** [comment]
Without optimizations the algorithm will run much slower (around 10 times is not unexpected), so you can try playing the bag at a much slower rate and see if the drift is less.
