### ISSUE TITLE
Measurement Jacobian

### ISSUE THREAD

**Issue by yuweijheng** [KumarRobotics/msckf_vio#43]
Thanks for sharing the code. 
I am wondering why is `dpc0_dxc.leftCols(3) = skewSymmetric(p_c0)`? Shouldn't it be `-R_w_c0 * skewSymmetric(d_theta) * (p_w - t_c0_w) = R_w_c0 * skewSymmetric(p_w - t_c0_w) * d_theta`? Thus, `dpc0_dxc.leftCols(3) = R_w_c0 * skewSymmetric(p_w - t_c0_w)`

**Comment by ke-sun** [comment]
The reason is that we use the left multiplication for the delta changes, i.e.
![codecogseqn](https://user-images.githubusercontent.com/8863049/41726342-ec073dee-753f-11e8-8491-26fc70dfab7f.gif)
instead of
![codecogseqn](https://user-images.githubusercontent.com/8863049/41726387-04b1f9a6-7540-11e8-9c67-898a317efdcf.gif)
where $\hat{R}$ represents the estimated orientation, while $dR$ stands for the difference between the estimated and the true orientation.

**Comment by yuweijheng** [comment]
Thanks for your reply!
Another question would be the entries of the matrix J in `stateAugmentation`.
The uncertainty representation for ![equation](http://latex.codecogs.com/gif.latex?\tilde{\mathbf{p}}^{w}_{c}) can be easily derived of the following form: 
![equation](http://latex.codecogs.com/gif.latex?\tilde{\mathbf{p}}^{w}_{c}=\tilde{\mathbf{p}}^{w}_{i}+\hat{\mathbf{R}}^{w}_{i}\left\lfloor\mathbf{p}^{i}_{c}\times\right\rfloor\tilde{\boldsymbol{\theta}}_{i}) 
(For some reasons, the results get worse than 
![equation](http://latex.codecogs.com/gif.latex?\tilde{\mathbf{p}}^{w}_{c}=\tilde{\mathbf{p}}^{w}_{i}+\left\lfloor\hat{\mathbf{R}}^{w}_{i}\mathbf{p}^{i}_{c}\times\right\rfloor\tilde{\boldsymbol{\theta}}_{i})
Thus, the corresponding code matches this formula as in the original MSCKF paper.)

But I am a bit confused how to derive the uncertainty representation for ![equation](http://latex.codecogs.com/gif.latex?\tilde{\boldsymbol{\theta}}_{c}=\mathbf{R}^{i}_{w}\tilde{\boldsymbol{\theta}}_{i})? I am not sure if this is a typo or similar reasons as above.  Can you briefly describe or walk me through how to derive the uncertainty representation for the orientation of camera?

Thanks.

**Comment by ke-sun** [comment]
My last impression was that the two equations resulted in similar accuracy. It sounds weird the results get worse in your case.

I think the correct transformation is 
![codecogseqn](https://user-images.githubusercontent.com/8863049/41783150-31c5e676-760a-11e8-9419-710bf80d6172.gif)
which leads to the error state relation as (assuming the cam-imu extrinsics is known),
![codecogseqn 1](https://user-images.githubusercontent.com/8863049/41783333-a10185b8-760a-11e8-872b-b39759db41f4.gif)
Hopefully, you would find it makes more sense this time.

**Comment by chutsu** [comment]
I could be completely wrong, but could the uncertainty representation for ![](https://camo.githubusercontent.com/63c09d39ebd2f5bd1cb7f956409baef0ce9a175d/687474703a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f25354374696c64652537422535436d617468626625374270253744253744253545253742772537445f25374263253744) have two different forms:
![1](https://user-images.githubusercontent.com/91460/41936677-f2d04060-795b-11e8-83c9-ebfe792b7895.png) (Mourikis's version) 
and
![2](https://user-images.githubusercontent.com/91460/41936731-299efdc0-795c-11e8-9775-d25104b0b529.png) (Sun's version)
because:
1. You "right multiplied" the delta
2. Used (eye(3) + skew(\tilde{\theta})) for small angle approx as supposed to (eye(3) - skew(\tilde{\theta})) (note: the minus.)

![screenshot_2018-06-26_15-21-32](https://user-images.githubusercontent.com/91460/41934553-08539b6e-7955-11e8-8281-dc7fd9ac2de2.png)

I may have made mistakes, please be kind!

**Comment by tomas789** [comment]
To answed the last question from the image, no, because of the angular error expressed in the body frame instead of the global frame. This is often called local or global angular error.

**Comment by symao** [comment]
Hi, i am confused about the difference in Jacobian of state augmentation. The $dp_c/dv$ is identity in Sun's paper while zeros in Mourikis's paper. Anyone know why?

**Comment by andylei77** [comment]
I think  the delta ![image](https://user-images.githubusercontent.com/19233114/62007381-4ea65f80-b17f-11e9-9a4b-c191300a0dd6.png) in https://github.com/KumarRobotics/msckf_vio/issues/43#issuecomment-400434979 by @chutsu is wrong, delta shoud be in the transpose.


True answer should be:
![image](https://user-images.githubusercontent.com/19233114/62007356-06873d00-b17f-11e9-8904-f9b7a62f96f5.png)


By the way, **why delta of JPL is "-"?**
**Because JPL is  Left-handed.**
 My derivation is follow: 
![image](https://user-images.githubusercontent.com/19233114/62007446-0fc4d980-b180-11e9-9452-5570c46ff70a.png)
