### ISSUE TITLE
Not publish at IMU rate?

### ISSUE THREAD

**Issue by kyumanlee84** [KumarRobotics/msckf_vio#55]
Hello, 

First, thanks for the open-source code.

I have following questions:
1. Does MSCKF publish odometry at image rate? Not at IMU rate? 
2. Does MSCKF publish odometry at the time when image was grabbed? Not real-time (or not at current time)?

The real-time high frequency VIO outputs might be crucial for UAV attitude control.

Thanks,

**Comment by ke-sun** [comment]
It does not publish the odom at the IMU rate but at the image rate.

Strictly speaking, it does not publish the odom exactly at the time when images are grabbed but a little behind since it requires time to do the calculation. However, the timestamp of the odom msg is set according to the corresponding image.
